url: "http://lyresdictionary.com"
baseurl: "/projects/lyres-dictionary"
title: "Lyre's Dictionary"
collections:
  pages:
    output: true
    permalink: /:title/
  blog:
    output: true
    permalink: /blog/:title/
