title: "Lyre's Dictionary"
description: "Lyre's Dictionary development blog."
url: "http://lyresdictionary.com"
baseurl: "projects/lyres-dictionary/"
collections:
  pages:
    output: true
    permalink: /:title/
  blog:
    output: true
    permalink: /blog/:title/
