title: "Lyre's Dictionary"
description: "Lyre's Dictionary development blog"
url: "http://inthescales.com"
collections:
  pages:
    output: true
    permalink: /:title/
  blog:
    output: true
    permalink: /blog/:title/
